//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHealthPass3.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientCorsOrigins = new HashSet<ClientCorsOrigin>();
            this.ClientPostLogoutRedirectUris = new HashSet<ClientPostLogoutRedirectUri>();
            this.ClientRedirectUris = new HashSet<ClientRedirectUri>();
        }
    
        public int Id { get; set; }
        public string ClientId { get; set; }
        public string ClientName { get; set; }
        public bool Enabled { get; set; }
        public int TokenLifetime { get; set; }
        public short MaxLoginAttemptsLock { get; set; }
        public short MaxLoginAttemptsLockout { get; set; }
        public int LockoutTimeSpan { get; set; }
        public short PasswordMinLength { get; set; }
        public bool PasswordRequireCaps { get; set; }
        public bool PasswordRequireDigit { get; set; }
        public bool PasswordRequireSpecialChar { get; set; }
        public bool IsDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientCorsOrigin> ClientCorsOrigins { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientPostLogoutRedirectUri> ClientPostLogoutRedirectUris { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientRedirectUri> ClientRedirectUris { get; set; }
    }
}
