//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyHealthPass3.DataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Person
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public System.DateTime Dob { get; set; }
        public string IsDeleted { get; set; }
        public System.DateTime DateCreated { get; set; }
        public System.DateTime LastUpdated { get; set; }
    
        public virtual User User { get; set; }
    }
}
